### ISSUE TITLE
Reflects assumptions about streamlines fix recommended (and incoming)

### ISSUE THREAD

**Issue by DanNBullock** [francopestilli/mba#16]
https://github.com/francopestilli/mba/blob/1f06c4bd86da41322d292bfb0318ab61efe8b4a5/compute/mbaComputeFiberLengthDistribution.m#L30

This computation assumes that (1) the nodes of streamlines are always 1mm spaced and (2) evenly spaced (such that each internode difference is equivalent).

Currently it is simply returning the number of nodes in all streamlines in an fg.

This is particularly a problem due to:
https://github.com/francopestilli/mba/blob/1f06c4bd86da41322d292bfb0318ab61efe8b4a5/compute/mbaRemoveFibersCoordsDistributionOutlier.m#L31
>if notDefined('numberOfNodes'), numberOfNodes=100; end

which resamples all streamlines to the same number of nodes

Recommended fix:
> streamsTotal=fg.fibers;
> Lmm =[];
> for istreamlines=1:length(fg.fibers)
>        Lmm(istreamlines)=sum(sqrt(sum(diff(streamsTotal{istreamlines},1,2).^2)));
>   end

(or some cellfun variant thereof to avoid the streamsTotal reassignment)

**Comment by francopestilli** [comment]
@DanNBullock sounds good slower but geenral can you please make a pull request?
I accepted your previous pull, so update the repo.

**Comment by DanNBullock** [comment]
ok, I should probably test it first though, will do that and then make request

**Comment by francopestilli** [comment]
yes pls
happy to test on my side too

**Comment by DanNBullock** [comment]
resolved: https://github.com/francopestilli/mba/pull/17

**Comment by DanNBullock** [comment]
Interesting epilogue to this story:

Apparently a similar issue was also included in MRtrix for a while:

https://github.com/MRtrix3/mrtrix3/commit/bbfdaeaa24762a6f43a8034aabc955d7b27a4c0f

But then they ended up getting a publication out of fixing it:

https://www.sciencedirect.com/science/article/pii/S105381192200859X
